services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: aqhub-app
    volumes:
      - ./:/var/www
      - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - aqhub

  server:
    image: nginx:alpine
    container_name: aqhub-server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - aqhub

networks:
  aqhub: