services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    container_name: aqhub-app
    ports:
      - "3000:8080"
    environment:
      SSL_MODE: "off"
    volumes:
      - ./:/var/www/html
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:17-alpine
    volumes:
      - dev_db_data:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql 
      - ./docker/inserts.sql:/docker-entrypoint-initdb.d/inserts.sql 
    container_name: aqhub-db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  dev_db_data:
    driver: local
