services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: aqhub-app
    volumes:
      - ./:/var/www
      - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - aqhub

  server:
    image: nginx:alpine
    container_name: aqhub-server
    ports:
      - "9000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - aqhub
      
  db:
    image: postgres:15-alpine
    container_name: aqhub-db
    restart: always
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: ${POSTGRES_DB}
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - aqhub

networks:
  aqhub:
