FROM serversideup/php:8.3-fpm-nginx

ENV PHP_OPCACHE_ENABLE="1" \
    PHP_OPCACHE_VALIDATE_TIMESTAMPS="0"

WORKDIR /var/www/html

COPY composer.json .

RUN composer install --no-dev --optimize-autoloader

COPY . .